node {
  stage('SCM') {
    checkout scm
  }
  stage('SonarQube Analysis') {
    def mvn = tool 'maven3';
    withSonarQubeEnv() {
      sh "${mvn}/bin/mvn clean verify sonar:sonar -Dsonar.projectKey=rest-docker-demo -Dsonar.projectName='rest-docker-demo' -Dsonar.java.binaries=target/classes"
    }
  }
}